// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD26E_zJb9MunsSTGT6wRLPn6JQy-waK2k',
    appId: '1:57919512010:web:b7560224c6a490eb81c333',
    messagingSenderId: '57919512010',
    projectId: 'handly-a5175',
    authDomain: 'handly-a5175.firebaseapp.com',
    storageBucket: 'handly-a5175.firebasestorage.app',
    measurementId: 'G-ZE0BY6P6B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP2hqI_o-6obbHU_Cts0C7CvmUs0tnvEU',
    appId: '1:57919512010:android:27c6469787d0aa0081c333',
    messagingSenderId: '57919512010',
    projectId: 'handly-a5175',
    storageBucket: 'handly-a5175.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDACSLQEW-5NEnjdB01liJ1SDkGwvJX9-w',
    appId: '1:57919512010:ios:88dc36c99ae8084781c333',
    messagingSenderId: '57919512010',
    projectId: 'handly-a5175',
    storageBucket: 'handly-a5175.firebasestorage.app',
    iosBundleId: 'com.example.handly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDACSLQEW-5NEnjdB01liJ1SDkGwvJX9-w',
    appId: '1:57919512010:ios:88dc36c99ae8084781c333',
    messagingSenderId: '57919512010',
    projectId: 'handly-a5175',
    storageBucket: 'handly-a5175.firebasestorage.app',
    iosBundleId: 'com.example.handly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD26E_zJb9MunsSTGT6wRLPn6JQy-waK2k',
    appId: '1:57919512010:web:732e0e8f2fbe481781c333',
    messagingSenderId: '57919512010',
    projectId: 'handly-a5175',
    authDomain: 'handly-a5175.firebaseapp.com',
    storageBucket: 'handly-a5175.firebasestorage.app',
    measurementId: 'G-XJLNS1K7ZK',
  );
}
